from __future__ import annotations
"""LLM-driven intent clarification module.

Single-LLM-call approach: the model decides whether to ask ONE clarification
question or to directly produce an enriched research prompt. Eliminates slot
detection, numbered parsing, and string-concatenation injection.

skip_clarification=True bypasses this module entirely (eval/batch mode).
"""

import json
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from deep_research.config.prompt_loader import get_prompt
from deep_research.core.agent import LLMClient
from deep_research.utils import extract_json_from_markdown

logger = logging.getLogger(__name__)


@dataclass
class ResearchPlanBrief:
    """Structured research plan brief shown to user for editing/confirmation.

    This is generated by the IntentClarifier and confirmed by the user before
    the full research pipeline begins. It serves as the north-star context
    that is re-injected at the final integration stage.
    """

    research_topic: str = ""
    research_background: str = ""
    research_objective: str = ""
    key_dimensions: list[str] = field(default_factory=list)
    time_scope: str = ""
    target_audience: str = ""
    expected_deliverable: str = ""

    def to_prompt_block(self) -> str:
        """Format as a Markdown block for prompt injection."""
        lines = [
            f"研究主题: {self.research_topic}",
            f"研究背景: {self.research_background}",
            f"研究目标: {self.research_objective}",
            f"核心分析维度: {', '.join(self.key_dimensions)}",
            f"时间范围: {self.time_scope}",
            f"目标受众: {self.target_audience}",
            f"预期产出: {self.expected_deliverable}",
        ]
        return "\n".join(lines)


@dataclass
class ClarificationResult:
    """Result of intent clarification analysis.

    When complete=True, plan_brief holds the structured research plan
    ready for user editing/confirmation.

    When complete=False, clarification_question holds the single question
    to ask the user (rare — only for truly ambiguous cases).
    """

    complete: bool
    original_query: str
    plan_brief: ResearchPlanBrief | None = None
    enriched_query: str = ""  # Backward compatibility
    clarification_question: str = ""
    rounds_completed: int = 0


_ANALYZE_SYSTEM_PROMPT = get_prompt("intent_clarifier", "analyze")

_INCORPORATE_SYSTEM_PROMPT = get_prompt("intent_clarifier", "incorporate")


class IntentClarifier:
    """LLM-driven intent clarification — single call per step."""

    MAX_ROUNDS = 2
    MAX_LLM_RETRIES = 2

    def __init__(self) -> None:
        self.llm = LLMClient()

    async def analyze(self, query: str) -> ClarificationResult:
        """Analyze query with a single LLM call.

        Returns ClarificationResult with either:
        - complete=True  + enriched_query (ready to research)
        - complete=False + clarification_question (one question for user)

        Falls back to complete=True with original query on LLM failure.
        """
        t0 = time.perf_counter()
        result = await self._analyze_with_retry(query)
        logger.info(
            f"[IntentClarifier] analyze in {time.perf_counter()-t0:.2f}s, "
            f"complete={result.complete}, query={query[:60]}..."
        )
        return result

    async def incorporate_response(
        self,
        original_query: str,
        clarification_question: str,
        user_response: str,
        existing_plan_brief: ResearchPlanBrief | None = None,
    ) -> ClarificationResult:
        """Incorporate user's answer to produce final enriched query.

        Always returns complete=True. Falls back to concatenation on failure.
        """
        t0 = time.perf_counter()
        result = await self._incorporate_with_retry(
            original_query, clarification_question, user_response, existing_plan_brief
        )
        logger.info(
            f"[IntentClarifier] incorporate_response in {time.perf_counter()-t0:.2f}s"
        )
        return result

    # ------------------------------------------------------------------
    # Internal: analyze
    # ------------------------------------------------------------------

    async def _analyze_with_retry(self, query: str) -> ClarificationResult:
        import asyncio
        last_error: Optional[Exception] = None
        for attempt in range(self.MAX_LLM_RETRIES + 1):
            try:
                result = await self._llm_analyze(query)
                if result is not None:
                    return result
            except Exception as e:
                last_error = e
                logger.warning(f"[IntentClarifier] analyze attempt {attempt+1} failed: {e}")
                if attempt < self.MAX_LLM_RETRIES:
                    await asyncio.sleep(2 ** attempt)

        logger.error(f"[IntentClarifier] analyze failed after all retries: {last_error}. Passthrough.")
        return ClarificationResult(complete=True, original_query=query, enriched_query=query)

    async def _llm_analyze(self, query: str) -> Optional[ClarificationResult]:
        today = datetime.now().strftime("%Y年%m月%d日")
        year = datetime.now().year

        user_prompt = f"""【当前日期】{today}

用户的原始研究请求：
{query}

请按以下逻辑处理：

**第一步：判断是否存在真正无法推断的关键歧义**

"真正无法推断"的标准（必须同时满足）：
1. 该信息的不同取值会导致研究方向根本不同
2. 无法从上下文、常识或当前日期合理推断
3. 只有用户本人才知道正确答案

**可自动补全的情况（不需要提问）：**
- 没有指定时间/年份 → 使用当前年份（{year}年）或"最新"
- 没有指定研究深度/范围 → 选择合理的全面分析
- 使用"最近""近期""最新"等词 → 理解为{year}年附近
- 没有指定报告格式 → 使用标准研究报告格式

**需要提问的情况（极少数）：**
- 名称真正有歧义且无法从语境判断（如孤立的"苹果"不知是公司还是水果）
- 研究对象完全缺失（用户只说"帮我分析一下"，没有任何主题）
- 两个完全不同的研究方向都合理且无法判断

**第二步：输出研究计划简报（Research Plan Brief）**

请从以下维度分析用户请求，生成一份结构化简报：

```json
{{
  "needs_clarification": false,
  "plan_brief": {{
    "research_topic": "一句话概括研究主题（20字以内）",
    "research_background": "为什么做这个研究？当前背景是什么？（50-80字）",
    "research_objective": "具体要解决什么问题？期望得出什么结论？（50-80字）",
    "key_dimensions": ["维度1", "维度2", "维度3"],
    "time_scope": "研究覆盖的时间范围",
    "target_audience": "报告的目标读者",
    "expected_deliverable": "预期产出形式和内容深度"
  }}
}}
```

如果确实需要向用户提问（极少数情况），输出：
```json
{{
  "needs_clarification": true,
  "clarification_question": "一句简洁的问题（30字以内）",
  "plan_brief": {{
    "research_topic": "...",
    "research_background": "...",
    "research_objective": "...",
    "key_dimensions": ["..."],
    "time_scope": "...",
    "target_audience": "...",
    "expected_deliverable": "..."
  }}
}}
```

**plan_brief 写作要求：**
- 研究主题：精炼的一句话，明确研究对象
- 研究背景：说明当前行业/市场/技术背景
- 研究目标：具体、可衡量的研究目的
- 核心维度：2-5个分析维度，覆盖用户关心的所有方面
- 时间范围：明确的数据截止时间
- 目标受众：帮助调整报告语言和深度
- 预期产出：描述报告应有的形式和详细程度
- 语言简洁专业，每个字段内容充实但不冗余"""

        messages = [
            {"role": "system", "content": _ANALYZE_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        response = await self.llm.chat(messages=messages)
        content = response["choices"][0]["message"].get("content", "")
        logger.debug(f"[IntentClarifier] LLM analyze raw: {content[:300]}")

        data = _parse_json(content)
        if data is None:
            logger.warning("[IntentClarifier] Failed to parse analyze response, using passthrough")
            return ClarificationResult(
                complete=True,
                original_query=query,
                plan_brief=ResearchPlanBrief(research_topic=query),
            )

        plan_data = data.get("plan_brief") or {}
        plan_brief = _build_plan_brief(plan_data, query)

        if data.get("needs_clarification"):
            question = str(data.get("clarification_question", "")).strip()
            if not question:
                return ClarificationResult(
                    complete=True,
                    original_query=query,
                    plan_brief=plan_brief,
                )
            return ClarificationResult(
                complete=False,
                original_query=query,
                plan_brief=plan_brief,
                clarification_question=question,
            )
        else:
            return ClarificationResult(
                complete=True,
                original_query=query,
                plan_brief=plan_brief,
            )

    # ------------------------------------------------------------------
    # Internal: incorporate_response
    # ------------------------------------------------------------------

    async def _incorporate_with_retry(
        self,
        original_query: str,
        clarification_question: str,
        user_response: str,
        existing_plan_brief: ResearchPlanBrief | None = None,
    ) -> ClarificationResult:
        import asyncio
        last_error: Optional[Exception] = None
        for attempt in range(self.MAX_LLM_RETRIES + 1):
            try:
                result = await self._llm_incorporate(
                    original_query, clarification_question, user_response, existing_plan_brief
                )
                if result is not None:
                    return result
            except Exception as e:
                last_error = e
                logger.warning(f"[IntentClarifier] incorporate attempt {attempt+1} failed: {e}")
                if attempt < self.MAX_LLM_RETRIES:
                    await asyncio.sleep(2 ** attempt)

        logger.error(f"[IntentClarifier] incorporate failed: {last_error}. Fallback.")
        return ClarificationResult(
            complete=True,
            original_query=original_query,
            plan_brief=existing_plan_brief or ResearchPlanBrief(research_topic=original_query),
            rounds_completed=1,
        )

    async def _llm_incorporate(
        self,
        original_query: str,
        clarification_question: str,
        user_response: str,
        existing_plan_brief: ResearchPlanBrief | None = None,
    ) -> Optional[ClarificationResult]:
        today = datetime.now().strftime("%Y年%m月%d日")
        year = datetime.now().year

        question_line = f"\n系统向用户提出的澄清问题：\n{clarification_question}\n" if clarification_question else ""
        existing_plan = f"\n之前生成的研究计划：\n{existing_plan_brief.to_prompt_block()}\n" if existing_plan_brief else ""

        user_prompt = f"""【当前日期】{today}

用户的原始研究请求：
{original_query}
{question_line}
用户的回答：
{user_response}
{existing_plan}

请将用户的回答融入原始请求，生成一份结构化的研究计划简报（Research Plan Brief）。

要求：
1. 完整保留原始请求的所有意图
2. 将用户的补充信息自然融入（不要显式标注"用户回答了XXX"）
3. 补充合理的时间范围（如没有指定，使用{year}年）
4. 明确研究深度和分析维度
5. 如果用户的回答是"随便""都行""默认"等，按最合理的方式处理

输出格式（JSON）：
```json
{{
  "plan_brief": {{
    "research_topic": "...",
    "research_background": "...",
    "research_objective": "...",
    "key_dimensions": ["..."],
    "time_scope": "...",
    "target_audience": "...",
    "expected_deliverable": "..."
  }}
}}
```"""

        messages = [
            {"role": "system", "content": _INCORPORATE_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        response = await self.llm.chat(messages=messages)
        content = response["choices"][0]["message"].get("content", "").strip()
        logger.debug(f"[IntentClarifier] LLM incorporate raw: {content[:200]}")

        data = _parse_json(content)
        if data is None:
            logger.warning("[IntentClarifier] Failed to parse incorporate response")
            return ClarificationResult(
                complete=True,
                original_query=original_query,
                plan_brief=existing_plan_brief or ResearchPlanBrief(research_topic=original_query),
                rounds_completed=1,
            )

        plan_data = data.get("plan_brief") or {}
        plan_brief = _build_plan_brief(plan_data, original_query)

        return ClarificationResult(
            complete=True,
            original_query=original_query,
            plan_brief=plan_brief,
            rounds_completed=1,
        )


def _build_plan_brief(data: dict, fallback_topic: str) -> ResearchPlanBrief:
    """Build ResearchPlanBrief from parsed JSON data."""
    return ResearchPlanBrief(
        research_topic=data.get("research_topic", fallback_topic) or fallback_topic,
        research_background=data.get("research_background", ""),
        research_objective=data.get("research_objective", ""),
        key_dimensions=data.get("key_dimensions") or [],
        time_scope=data.get("time_scope", ""),
        target_audience=data.get("target_audience", ""),
        expected_deliverable=data.get("expected_deliverable", ""),
    )


def _parse_json(content: str) -> Optional[dict]:
    """Extract and parse JSON from LLM response."""
    try:
        return json.loads(extract_json_from_markdown(content).lstrip("\ufeff"))
    except (json.JSONDecodeError, IndexError, ValueError) as e:
        logger.warning(f"[IntentClarifier] JSON parse failed: {e}, content={content[:200]}")
        return None
