"""Research plan execution: DAG of tasks with parallel scheduling.

A ResearchPlan is a directed acyclic graph (DAG) of TaskNodes.
The DAGScheduler topologically sorts the graph and executes ready
nodes in parallel while respecting dependencies.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Callable

from deep_research.core.finding import Finding

logger = logging.getLogger(__name__)

# Maximum concurrent workers to avoid API rate limits
DEFAULT_MAX_PARALLEL = 3
DEFAULT_MAX_RETRIES = 2


@dataclass
class TaskNode:
    """A single research task in the plan DAG."""

    task_id: str
    role: str  # e.g. "tavily_search", "data_fetch", "doc_analysis", "cross_verify", "synthesis"
    goal: str
    depends_on: list[str] = field(default_factory=list)
    inputs: dict[str, Any] = field(default_factory=dict)
    status: str = "pending"  # pending | running | completed | failed
    output: Finding | None = None
    retry_count: int = 0
    error_message: str = ""

    def is_ready(self, completed_ids: set[str]) -> bool:
        """Check if all dependencies are satisfied."""
        return all(dep in completed_ids for dep in self.depends_on)

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "role": self.role,
            "goal": self.goal,
            "depends_on": self.depends_on,
            "inputs": self.inputs,
            "status": self.status,
            "output": self.output.to_dict() if self.output else None,
            "retry_count": self.retry_count,
            "error_message": self.error_message,
        }


@dataclass
class ResearchPlan:
    """A DAG of research tasks generated by the Planner."""

    plan_id: str
    user_query: str
    tasks: list[TaskNode]
    strategy: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def get_ready_tasks(self) -> list[TaskNode]:
        """Return tasks whose dependencies are all satisfied (completed or failed)."""
        satisfied_ids = {
            t.task_id for t in self.tasks
            if t.status in ("completed", "failed")
        }
        return [
            t for t in self.tasks
            if t.status == "pending" and t.is_ready(satisfied_ids)
        ]

    def get_completed_tasks(self) -> list[TaskNode]:
        return [t for t in self.tasks if t.status == "completed"]

    def get_failed_tasks(self) -> list[TaskNode]:
        return [t for t in self.tasks if t.status == "failed" and t.retry_count >= DEFAULT_MAX_RETRIES]

    def is_complete(self) -> bool:
        """True when every task is either completed or exhausted retries."""
        return all(
            t.status in ("completed", "failed")
            for t in self.tasks
        )

    def is_fully_successful(self) -> bool:
        return all(t.status == "completed" for t in self.tasks)

    def get_findings(self) -> list[Finding]:
        """All completed task outputs."""
        return [t.output for t in self.tasks if t.output is not None]

    def to_planner_context(self) -> str:
        """Token-efficient summary for Planner evaluation."""
        lines = [f"Plan: {self.plan_id} | Query: {self.user_query}"]
        for t in self.tasks:
            status_emoji = {
                "pending": "⏳", "running": "🔄",
                "completed": "✅", "failed": "❌",
            }.get(t.status, "❓")
            if t.output:
                lines.append(f"  {status_emoji} {t.task_id} [{t.role}]: {t.output.to_planner_context()}")
            else:
                lines.append(f"  {status_emoji} {t.task_id} [{t.role}]: {t.status}")
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "user_query": self.user_query,
            "strategy": self.strategy,
            "metadata": self.metadata,
            "tasks": [t.to_dict() for t in self.tasks],
        }


class DAGScheduler:
    """Executes a ResearchPlan respecting dependency DAG."""

    def __init__(self, max_parallel: int = DEFAULT_MAX_PARALLEL, max_retries: int = DEFAULT_MAX_RETRIES) -> None:
        self.max_parallel = max_parallel
        self.max_retries = max_retries

    async def execute(
        self,
        plan: ResearchPlan,
        worker_factory: Callable[[TaskNode], Callable[..., asyncio.Future]],
    ) -> list[Finding]:
        """Execute plan until completion or deadlock.

        Args:
            plan: The research plan DAG.
            worker_factory: Callable that takes a TaskNode and returns
                a coroutine/future that produces a Finding.

        Returns:
            List of all successful findings.
        """
        logger.info(f"[Scheduler] Starting plan {plan.plan_id} with {len(plan.tasks)} tasks, max_parallel={self.max_parallel}")
        total_t0 = time.perf_counter()
        round_num = 0

        while not plan.is_complete():
            round_num += 1
            ready = plan.get_ready_tasks()

            if not ready:
                # No ready tasks but not complete -> deadlock or all remaining blocked
                failed = [t for t in plan.tasks if t.status == "failed"]
                pending = [t for t in plan.tasks if t.status == "pending"]
                logger.warning(
                    f"[Scheduler] Deadlock detected: {len(failed)} failed, {len(pending)} pending"
                )
                break

            # Limit parallelism
            batch = ready[:self.max_parallel]
            logger.info(f"[Scheduler] Round {round_num}: executing {len(batch)} tasks: {[t.task_id for t in batch]}")

            # Mark as running
            for t in batch:
                t.status = "running"

            # Execute batch in parallel
            batch_t0 = time.perf_counter()
            results = await asyncio.gather(
                *[self._run_task(t, worker_factory) for t in batch],
                return_exceptions=True,
            )
            batch_latency = time.perf_counter() - batch_t0
            logger.info(f"[Scheduler] Round {round_num} completed in {batch_latency:.2f}s for tasks {[t.task_id for t in batch]}")

            # Process results
            for task, result in zip(batch, results):
                if isinstance(result, Exception):
                    task.status = "failed"
                    task.retry_count += 1
                    task.error_message = str(result)
                    if task.retry_count <= self.max_retries:
                        logger.warning(f"[Scheduler] Task {task.task_id} failed (attempt {task.retry_count}), will retry: {result}")
                        task.status = "pending"  # Retry in next round
                    else:
                        logger.error(f"[Scheduler] Task {task.task_id} exhausted retries: {result}")
                else:
                    task.status = "completed"
                    task.output = result
                    task.error_message = ""
                    logger.info(f"[Scheduler] Task {task.task_id} completed: {result.summary}")

        total_latency = time.perf_counter() - total_t0
        findings = plan.get_findings()
        logger.info(
            f"[Scheduler] Plan {plan.plan_id} finished in {total_latency:.2f}s: "
            f"{len(findings)}/{len(plan.tasks)} tasks succeeded, rounds={round_num}"
        )
        return findings

    async def _run_task(
        self,
        task: TaskNode,
        worker_factory: Callable[[TaskNode], Callable[..., asyncio.Future]],
    ) -> Finding:
        """Run a single task via the worker factory."""
        worker = worker_factory(task)
        return await worker()
